//! A2.9 chat-template parity: byte-identical rendering against the
//! Jinja2-derived goldens in `tests/fixtures/golden-templates.json`
//! (generated by `tests/fixtures/gen_template_fixtures.py`; oracle notes in
//! `tests/fixtures/templates.json`).
//!
//! Covers every reference template (llama3, qwen25, mistral) over the full
//! context matrix, including failure parity (the mistral `tool_roundtrip`
//! case raises in both engines) and render-twice repeatability.

use r9v_loader::{ChatContext, ChatMessage, ToolCall};
use serde_json::Value;

mod common;
use common::ordered_json::{self, OrderedValue};

fn fixture_dir() -> String {
    format!("{}/tests/fixtures", env!("CARGO_MANIFEST_DIR"))
}

fn str_field(v: &OrderedValue, key: &str) -> String {
    v.get(key).and_then(|f| f.as_str()).unwrap_or("").to_owned()
}

fn message(v: &OrderedValue) -> ChatMessage {
    let mut m = ChatMessage {
        role: str_field(v, "role"),
        content: str_field(v, "content"),
        tool_calls: Vec::new(),
        reasoning_content: None,
    };
    if let Some(calls) = v.get("tool_calls").and_then(|c| c.as_array()) {
        for call in calls {
            let function = call.get("function");
            m.tool_calls.push(ToolCall {
                name: function.map(|f| str_field(f, "name")).unwrap_or_default(),
                arguments: function
                    .map(|f| str_field(f, "arguments"))
                    .unwrap_or_default(),
                id: call.get("id").and_then(|i| i.as_str()).map(str::to_owned),
            });
        }
    }
    m
}

fn render_case(tmpl: &str, ctx_name: &str, contexts: &OrderedValue) -> Result<String, String> {
    let dir = fixture_dir();
    let source = std::fs::read_to_string(format!("{dir}/template-{tmpl}.jinja")).unwrap();
    let ctx = contexts.get(ctx_name).expect("context must exist");
    let mut chat = ChatContext {
        messages: ctx
            .get("messages")
            .and_then(|m| m.as_array())
            .unwrap()
            .iter()
            .map(message)
            .collect(),
        add_generation_prompt: ctx
            .get("add_generation_prompt")
            .and_then(|f| f.as_bool())
            .unwrap(),
        bos_token: ctx
            .get("bos_token")
            .and_then(|f| f.as_str())
            .map(str::to_owned),
        eos_token: ctx
            .get("eos_token")
            .and_then(|f| f.as_str())
            .map(str::to_owned),
        enable_thinking: None,
        tools: None,
        tool_choice: None,
        extra: Default::default(),
    };
    if let Some(tools) = ctx.get("tools") {
        chat.tools = Some(ordered_json::to_template_value(tools));
    }
    r9v_loader::render_chat_template(&source, &chat).map_err(|e| e.to_string())
}

fn golden_cases() -> (Value, OrderedValue) {
    let dir = fixture_dir();
    let golden: Value = serde_json::from_str(
        &std::fs::read_to_string(format!("{dir}/golden-templates.json")).unwrap(),
    )
    .unwrap();
    // Contexts parse order-preservingly: `.items()` iteration order is part
    // of the oracle contract.
    let contexts =
        OrderedValue::parse(&std::fs::read_to_string(format!("{dir}/contexts.json")).unwrap())
            .unwrap();
    (golden, contexts)
}

/// Every golden case renders byte-identically (or fails, exactly when the
/// oracle fails).
#[test]
fn golden_parity() {
    let (golden, contexts) = golden_cases();
    let cases = golden["cases"].as_array().unwrap();
    assert_eq!(
        cases.len(),
        15,
        "golden matrix must cover 3 templates x 5 contexts"
    );
    for case in cases {
        let tmpl = case["template"].as_str().unwrap();
        let ctx_name = case["context"].as_str().unwrap();
        let label = format!("{tmpl}/{ctx_name}");
        match render_case(tmpl, ctx_name, &contexts) {
            Ok(got) => {
                assert_eq!(
                    case["status"].as_str().unwrap(),
                    "ok",
                    "{label}: oracle failed but we rendered"
                );
                assert_eq!(
                    got,
                    case["output"].as_str().unwrap(),
                    "{label}: byte mismatch"
                );
            }
            Err(err) => {
                assert_eq!(
                    case["status"].as_str().unwrap(),
                    "error",
                    "{label}: oracle rendered but we failed: {err}"
                );
            }
        }
    }
}

/// Rendering is deterministic: two passes over every ok case agree byte-wise.
#[test]
fn repeatability() {
    let (golden, contexts) = golden_cases();
    for case in golden["cases"].as_array().unwrap() {
        if case["status"].as_str().unwrap() != "ok" {
            continue;
        }
        let tmpl = case["template"].as_str().unwrap();
        let ctx_name = case["context"].as_str().unwrap();
        let first = render_case(tmpl, ctx_name, &contexts).unwrap();
        let second = render_case(tmpl, ctx_name, &contexts).unwrap();
        assert_eq!(first, second, "{tmpl}/{ctx_name}: render not repeatable");
    }
}
